on:
  push
jobs:
  build:
    runs-on: windows-2019
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: cygwin/cygwin-install-action@master
      - run: |
          apt-cyg install -y curl tar
      - run: |
          bash.exe curl -L https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/opam64.tar.xz --output opam64.tar.xz
          bash.exe tar -xf opam64.tar.xz
          bash.exe opam32/install.sh
          bash.exe opam init default "https://github.com/fdopen/opam-repository-mingw.git#opam2" -c "ocaml-variants.4.07.1+mingw64c" --disable-sandboxing
      - run: |
          bash.exe unset OPAMROOT
          bash.exe make

